server:
  port: 80
spring:
  application:
    name: consul-consumer-payment
  ###  下面几行的意思是 将当前的80服务 以"consul-consumer-payment" 的名称注册到 consul 注册中心（localhost:8500）
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
