server:
  port: 8006
spring:
  ## 服务名称
  application:
    name: consul-provider-payment           # 使用 consul-provider-payment 作为服务名（consul 客户端）
  ###  下面几行的意思是 将当前的8006服务 以"consul-provider-payment" 的名称注册到 consul 注册中心（localhost:8500）
  cloud:
    consul:                                 # 配置当前服务器作为客户端 连接的 consul 服务端地址
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
