server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: org.gjt.mm.mysql.Driver     # mysql 5.1.47
    driver-class-name: com.mysql.jdbc.Driver      # mysql 5.1.47
    #driver-class-name: com.mysql.cj.jdbc.Driver   # mysql  8.0.18
    #url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    url: jdbc:mysql://localhost:3306/seata_order?serverTimezone=GMT
    username: root
    password: root

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:mapper/*.xml
